### ISSUE TITLE
OpenCenter Database Problem

### ISSUE THREAD

**Issue by ryanyard** [rcbops/opencenter#435]
Fresh install of CentOS 6.3, ran a yum -y update, then: 

curl -L "https://sh.opencenter.rackspace.com/install.sh" | \
sudo bash -s server

When I run opencenter node list, I get the following error:

DEBUG:migrate.versioning.repository:Loading repository /usr/lib/python2.6/site-packages/opencenter/db/migrate_repo...
DEBUG:migrate.versioning.script.base:Loading script /usr/lib/python2.6/site-packages/opencenter/db/migrate_repo/versions/001_initial_data.py...
DEBUG:migrate.versioning.script.base:Script /usr/lib/python2.6/site-packages/opencenter/db/migrate_repo/versions/001_initial_data.py loaded successfully
DEBUG:migrate.versioning.repository:Repository /usr/lib/python2.6/site-packages/opencenter/db/migrate_repo loaded successfully
DEBUG:migrate.versioning.repository:Config: {'db_settings': {'**name**': 'db_settings', 'required_dbs': '[]', 'version_table': 'migrate_version', 'repository_id': 'OpenCenter Migrations'}}
DEBUG:migrate.versioning.util:Disposing SQLAlchemy engine Engine(sqlite:///)
DEBUG:migrate.versioning.util:Disposing SQLAlchemy engine Engine(sqlite:///)
DEBUG:migrate.versioning.util:Disposing SQLAlchemy engine Engine(sqlite:///)
Traceback (most recent call last):
  File "/usr/bin/opencenter", line 9, in <module>
    load_entry_point('python-opencenter==1.0.0', 'console_scripts', 'opencenter')()
  File "/usr/lib/python2.6/site-packages/opencenter/**init**.py", line 77, in main
    init_db(server.config['database_uri'])
  File "/usr/lib/python2.6/site-packages/opencenter/db/database.py", line 55, in init_db
    migrate_db(engine, *_kwargs)
  File "/usr/lib/python2.6/site-packages/opencenter/db/database.py", line 97, in migrate_db
    db_ver = migrate_api.db_version(uri, repo_path)
  File "<string>", line 2, in db_version
  File "/usr/lib/python2.6/site-packages/migrate/versioning/util/**init**.py", line 160, in with_engine
    return f(_a, *_kw)
  File "/usr/lib/python2.6/site-packages/migrate/versioning/api.py", line 147, in db_version
    schema = ControlledSchema(engine, repository)
  File "/usr/lib/python2.6/site-packages/migrate/versioning/schema.py", line 31, in **init**
    self.load()
  File "/usr/lib/python2.6/site-packages/migrate/versioning/schema.py", line 43, in load
    self.table = Table(tname, self.meta, autoload=True)
  File "/usr/lib64/python2.6/site-packages/SQLAlchemy-0.7.8-py2.6-linux-x86_64.egg/sqlalchemy/schema.py", line 318, in **new**
    table._init(name, metadata, *args, *_kw)
  File "/usr/lib64/python2.6/site-packages/SQLAlchemy-0.7.8-py2.6-linux-x86_64.egg/sqlalchemy/schema.py", line 381, in _init
    self._autoload(metadata, autoload_with, include_columns)
  File "/usr/lib64/python2.6/site-packages/SQLAlchemy-0.7.8-py2.6-linux-x86_64.egg/sqlalchemy/schema.py", line 408, in _autoload
    self, include_columns, exclude_columns
  File "/usr/lib64/python2.6/site-packages/SQLAlchemy-0.7.8-py2.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 2426, in run_callable
    return conn.run_callable(callable_, _args, *_kwargs)
  File "/usr/lib64/python2.6/site-packages/SQLAlchemy-0.7.8-py2.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1969, in run_callable
    return callable_(self, _args, *_kwargs)
  File "/usr/lib64/python2.6/site-packages/SQLAlchemy-0.7.8-py2.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 260, in reflecttable
    return insp.reflecttable(table, include_columns, exclude_columns)
  File "/usr/lib64/python2.6/site-packages/SQLAlchemy-0.7.8-py2.6-linux-x86_64.egg/sqlalchemy/engine/reflection.py", line 412, in reflecttable
    raise exc.NoSuchTableError(table.name)
migrate.versioning.exceptions.DatabaseNotControlledError: migrate_version

**Comment by ryanyard** [comment]
I am an idiot, I realized, I need to use opencentercli node list, not just opencenter
